# Generated by Django 3.0.8 on 2020-07-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.CharField(max_length=50)),
                ('heroien', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=20)),
                ('budget', models.IntegerField(null=True)),
                ('reldate', models.DateField(null=True)),
            ],
        ),
    ]
