# Generated by Django 3.0.8 on 2020-07-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('mailid', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(null=True)),
            ],
        ),
    ]
